name: ioasys_empresas_flutter
description: Desafio Técnico Ioasys - Pessoa Desenvolvedora Flutter.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^4.5.1+1
  flutter_mobx: ^2.0.4
  mobx: ^2.0.6+1
  dio: ^4.0.6
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  mobx_codegen: ^2.0.2
  modular_codegen: ^3.0.2
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - fonts/
    - assets/
    - assets/images/logo.png
    - assets/images/background.png
    - assets/images/logo-markdown.png
    - assets/images/loading.gif
    - assets/images/not-found.png
    - assets/icon/icon.png

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-ExtraBold.otf
    - family: Gilroy Light
      fonts:
        - asset: fonts/Gilroy-Light.otf
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs